framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    form: ~
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        cookie_httponly: ~
    fragments:       ~
    http_method_override: true
    serializer: { enabled: true }

twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

