login:
    path: /login
    defaults:
        _controller: AppBundle:Index:login

hwi_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

login_check:
    path: /login_check

logout:
    path: /logout

public:
    resource: "@AppBundle/Resources/config/routing/public.yml"
    prefix: /{_locale}/
    requirements:
        _locale: en|nl
    type: rest

admin:
    resource: "@AppBundle/Resources/config/routing/admin.yml"
    prefix: /admin
    type: rest

plugin:
    resource: "@PluginBundle/Resources/config/routing.yml"
    type: rest

home:
    path: /
    defaults:
        _controller: AppBundle:Index:index
