admin_form:
    resource: "AppBundle:Admin/Form"
    type: rest
    name_prefix: admin_
admin_enrollment:
    resource: "AppBundle:Admin/Enrollment"
    type: rest
    name_prefix: admin_
    parent: admin_form

admin_docs:
    resource: AppBundle:Admin/Documentation
    type: rest
    name_prefix: admin_
    requirements:
        doc: '.+'
    defaults:
        _format: null
