<?php

namespace PluginBundle\Entity;
use AppBundle\Entity\Enrollment;
use AppBundle\Entity\Form;
use Doctrine\ORM\EntityRepository;

/**
 * EnrollmentCountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnrollmentCountRepository extends EntityRepository
{
    /**
     * @param Form $form
     * @return int
     */
    public function getEnrollmentCount(Form $form)
    {
        return $this->createQueryBuilder('ec')
            ->select('SUM(ec.count)')
            ->where('ec.form = :form')
            ->setParameter('form', $form)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function setEnrollmentCount(Enrollment $enrollment, $count)
    {
        $enrollmentCount = $this->find($enrollment);
        if(!$enrollmentCount) {
            $this->addEnrollmentCount($enrollment, $count);
        } else {
            $enrollmentCount->setCount($count);
        }
    }

    public function addEnrollmentCount(Enrollment $enrollment, $count)
    {
        $enrollmentCount = new EnrollmentCount($enrollment);
        $enrollmentCount->setCount($count);
        $this->_em->persist($enrollmentCount);
    }
}
